volumes:
  postgres-data:
    name: postgres-data
  pgadmin-data:
    name: pgadmin-data

networks:
  cava-network:
    name: cava-network
    driver: bridge

services:
  pgadmin:
    profiles: [ "default"]
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    networks:
      - cava-network
    environment:
      PGADMIN_DEFAULT_EMAIL: a@b.c
      PGADMIN_DEFAULT_PASSWORD: pwd
      SCRIPT_NAME: /pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"

  cava-database:
    profiles: [ "default", "jupyter"]
    build: ./postgres
    container_name: cava-database
    networks:
      - cava-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/home/data:rw
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
  cava-jupyter-notebook:
    profiles: [ "jupyter"]
    build: ./jupyter
    restart: unless-stopped
    container_name: cava-jupyter-notebook
    depends_on:
      - cava-database
    networks:
      - cava-network
    environment:
      JUPYTERHUB_SERVICE_PREFIX: /jupyter/
      JUPYTERHUB_BASE_URL: ${HTTP_TYPE}://${HOST}
    env_file:
      - .env
    volumes:
      - ./work:/home/jovyan/work:rw
      - ${PYTHON_BIND_MOUNT}:/app/data
    command:
      - jupyter-lab
      - --ip=*
      - --NotebookApp.token=
      - --NotebookApp.password=
      - --NotebookApp.base_url=/jupyter
    ports:
      - "8888:8888" 
    mem_limit: 12g
    shm_size: 4g